name: Tests
on: 
  repository_dispatch:
    types: [tests-report]
  push:
jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest]  # mac-os currently in progress
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Build wasm files
        run: source scripts/flags.sh && rustup target add wasm32-unknown-unknown && cargo build --all --target wasm32-unknown-unknown --release && cp target/wasm32-unknown-unknown/release/*.wasm ./res/
      - name: Run unit tests
        env:
          IS_GITHUB_ACTION: true
        run: cd nft && cargo test -- --nocapture --color=always
      - name: Run Rust integration tests
        run: cd integration-tests/rs && cargo run --example integration-tests
      - name: Run TypeScript integration tests
        run: cd integration-tests/ts && npm i && npm run test 
