
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: RUST CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            # override: true
            components: rustfmt, clippy, cargo

      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser


      - name: run helper test
        run: |
          ls
          cd ./src/helper/
          cargo test --lib

      - name: run near_nft test
        run: |
          ls
          cd ./src/near_nft/
          rustup target add wasm32-unknown-unknown
          cargo install cargo-near 
          ./scripts/test.sh

      
